### ISSUE TITLE
[Bug] 1.2.1 has "latest-release" instead of "latest" tag forcing 1.1.0 download

### ISSUE THREAD

**Issue by dethmourne** [TychoTheTaco/Twitch-Drops-Bot#124]
**Describe the bug**
If you use the default docker command as described in the readme.md to run the container, then instead of running 1.2.1 you end up redownloading 1.1.0 - this is because (at least on Docker for Windows) the "latest-release" tag is not the same as the "latest" tag, and "latest" takes priority. You can work around this by adding :latest-release to the end of the container name.

**Comment by TychoTheTaco** [comment]
Good catch, I will update the readme. 

One thing to note though, `latest` will always be newer than (or the same as) `latest-release`, so if `latest-release` is `1.2.1`, then without specifying a tag, it would redownload `latest`, which would also be at least `1.2.1`. I'm guessing what happened to you is that you pulled the new `latest-release` version, then started the container without a tag (which would default to `latest`), and since you already had that one previously it would start it (without pulling the newer `latest` version).

**Comment by dethmourne** [comment]
Weird – so for me, I -had- 1.1.0, and then I downloaded 1.2.1, but then it ran 1.1.0 when I ran it without a tag. I then deleted my 1.1.0 thinking it would just failover to 1.2.1 – but instead it redownloaded 1.1.0 without a tag. I had to explicitly use :latest-release to run 1.2.1 instead of 1.1.0. Why that is, I honestly couldn’t tell you, and it sounds like it should never do that based on your explanation.
