### ISSUE TITLE
interval 

### ISSUE THREAD

**Issue by xCorteX** [TychoTheTaco/Twitch-Drops-Bot#19]
interval option does not work properly, the bot set Sleeptime to 3.6 min

> [2021-11-14 21:30:45] [debug] final minlastdropcampaignchecktime: 1636921761401 time: 1636921845514
> [2021-11-14 21:30:45] [debug] 300000 84113
> [2021-11-14 21:30:45] [info] No campaigns/streams active. Sleeping for 3.6 min.
> [2021-11-14 21:30:45] [debug] waiting for waitNotify

	
	"browser":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
	"games":["490377", "491931", "30921"],
	"headless":true,
	"headless_login":false,
	"interval": 15,
	"browser_args":[""],
	"watch_unlisted_games":false,
	"cookies_path":"cookies-xxx.json"

**Comment by TychoTheTaco** [comment]
As of the latest update, there are actually 2 different intervals.

The one that is configured by the config file defines how often the app checks for new drop campaigns. 

The other one determines how often to check for online streams on drop campaigns that are already active. This one is currently not configurable but is set to 5 minutes. This means if the app is not currently watching any streams, it will check each currently active drop campaign every 5 minutes to see if there are any streams online. In your case it was 3.6 minutes since the app last checked 1.4 minutes ago.

**Comment by xCorteX** [comment]
ah ok, thanks for the answer

issue can be closed
